EXPERIMENT:
  NAME: ""
  TAG: "ikl_kd,res50,mobilenetv1"
  PROJECT: "imagenet"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 48
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "IKL_KD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 512 
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
IKL_KD:
  ALPHA: 4.0 
  BETA: 1.0
  GI: True
  T2: 1.0
