algorithm: refixmatch
save_dir: ./saved_models/usb_cv
save_name: refixmatch_cifar100_200_0
resume: True
load_path: ./saved_models/usb_cv/refixmatch_cifar100_200_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 200
num_train_iter: 204800
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 200
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 5e-05
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: vit_small_patch2_32
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10006
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/vit_small_patch2_32_mlp_im_1k_32.pth
