EXPERIMENT:
  NAME: ""
  TAG: "ikl,vgg13,mv2"
  PROJECT: "cifar100"
DISTILLER:
  TYPE: "IKL_KD"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
IKL_KD:
  NUM_CLASSES: 100
  ALPHA: 4.0
  BETA: 12.0
  T: 4.0
  WARMUP: 20
