algorithm: simmatch
save_dir: ./saved_models/classic_cv
save_name: simmatch_imagenet_100k_0
resume: True
load_path: ./saved_models/classic_cv/simmatch_imagenet_100k_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1024
num_train_iter: 1048576
num_log_iter: 1024
num_eval_iter: 5120
num_labels: 100000
batch_size: 128
eval_batch_size: 256
p_cutoff: 0.7
in_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 128
K: 100000
da_len: 256
smoothing_alpha: 0.9
uratio: 1
T: 0.1
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
use_epass: True
net: resnet50
net_from_name: False
data_dir: /home
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10053
dist_backend: nccl
gpu: None
