#!/bin/bash
#SBATCH --job-name=semi_soft
#SBATCH --mail-user=jqcui@cse.cuhk.edu.hk
#SBATCH --mail-type=ALL
#SBATCH --output=semi_soft
#SBATCH --gres=gpu:1
#SBATCH -c 4 
#SBATCH -p dvlab 
#SBATCH -w proj200

source activate usb 

python train.py --c config/usb_cv/fixmatch/fixmatch_cifar100_200_0.yaml
